version: "3.9"

services:
  internship-scraper:
    build: .
    container_name: internship-scraper
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./data:/app/data
    working_dir: /app
